<?php

    namespace ForumBundle\Entity\Repository;

    use Doctrine\ORM\EntityRepository;

    /**
     * CategoryRepository
     *
     * This class was generated by the Doctrine ORM. Add your own custom
     * repository methods below.
     */
    class CategoryRepository extends \Doctrine\ORM\EntityRepository
    {
        public function findAllCategories()
        {
            return $this->getEntityManager()
                ->createQuery('SELECT c FROM ForumBundle:Category c WHERE c.isPosted = 1')
                ->getResult();
        }
    }
