<?php

    namespace ForumBundle\Entity\Repository;

    /**
     * SubcategoryRepository
     *
     * This class was generated by the Doctrine ORM. Add your own custom
     * repository methods below.
     */
    class SubcategoryRepository extends \Doctrine\ORM\EntityRepository
    {
        public function findAllSubcategories()
        {
            return $this->getEntityManager()
                ->createQuery('SELECT s FROM ForumBundle:Subcategory s WHERE s.isPosted = 1')
                ->getResult();
        }

        public function findSubcategoriesByCategory($category)
        {
            return $this->getEntityManager()
                ->createQuery('SELECT s, c FROM ForumBundle:Subcategory s JOIN s.category c WHERE c.hyphenation = :category')
                ->setParameter('category', $category)
                ->getResult();
        }
    }
