<?php

    namespace ForumBundle\Entity\Repository;

    /**
     * TopicRepository
     *
     * This class was generated by the Doctrine ORM. Add your own custom
     * repository methods below.
     */
    class TopicRepository extends \Doctrine\ORM\EntityRepository
    {
        public function findAllTopics($category, $subcategory)
        {
            return $this->getEntityManager()
                ->createQuery('SELECT t, s, c FROM ForumBundle:Topic t JOIN t.subcategory s JOIN s.category c WHERE c.hyphenation = :category AND s.hyphenation = :subcategory')
                ->setParameter('category', $category)
                ->setParameter('subcategory', $subcategory)
                ->getResult();
        }
    }
