<?php

    namespace ForumBundle\Entity\Repository;

    use Doctrine\ORM\EntityRepository;

    /**
     * UserRepository
     *
     * This class was generated by the Doctrine ORM. Add your own custom
     * repository methods below.
     */
    class UserRepository extends \Doctrine\ORM\EntityRepository
    {
        public function findOnlineUsers()
        {
            $delay = new \DateTime();
            $delay->setTimestamp(strtotime('2 minutes ago'));

            return $this->getEntityManager()
                ->createQuery('SELECT u FROM ForumBundle:User u WHERE u.lastActivityAt > :delay')
                ->setParameter('delay', $delay)
                ->getResult();
        }

        public function findTotalUser()
        {
            return $this->getEntityManager()
                ->createQuery('SELECT COUNT(u.id) FROM ForumBundle:User u')
                ->getSingleScalarResult();
        }

        public function findLastUserRegistered()
        {
            return $this->getEntityManager()
                ->createQuery('SELECT u FROM ForumBundle:User u ORDER BY u.registered_at DESC')
                ->setMaxResults(1)
                ->getSingleResult();
        }
    }
